services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:${VERSION}
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
      - UMASK=0022
    volumes:
      - ${CONFIGPATH}:/config
      - ${DATAPATH}:/data
    restart: unless-stopped
    networks:
      - proxy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.sonarr.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.sonarr.entrypoints=websecure
      - traefik.http.routers.sonarr.tls.certresolver=myresolver
      - traefik.http.services.sonarr.loadbalancer.server.port=8989
networks:
  proxy-network:
    external: true
