services:
  qbittorrent-nox:
    # for debugging
    #cap_add:
    #- SYS_PTRACE
    # additional arguments to `qbittorrent-nox`
    #command:
    #- --help
    container_name: qbittorrent-nox
    restart: unless-stopped
    environment:
      - PGID=1000
      - PUID=1000
      - QBT_LEGAL_NOTICE=${LEGALNOTICE}
      - QBT_VERSION=${VERSION}
      - QBT_TORRENTING_PORT=${TORRENTINGPORT}
      - QBT_WEBUI_PORT=8080
      - TZ=Europe/Budapest
      - UMASK=022
    image: qbittorrentofficial/qbittorrent-nox:${VERSION}
    ports:
      - ${TORRENTINGPORT}:${TORRENTINGPORT}/tcp
      - ${TORRENTINGPORT}:${TORRENTINGPORT}/udp
    read_only: true
    stop_grace_period: 30m
    tmpfs:
      - /tmp
    tty: true
    volumes:
      - ${CONFIGPATH}:/config
      - ${DOWNLOADSPATH}:/data
    networks:
      - proxy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.qbittorrent.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.qbittorrent.entrypoints=websecure
      - traefik.http.routers.qbittorrent.tls.certresolver=myresolver
      - traefik.http.services.qbittorrent.loadbalancer.server.port=8080
networks:
  proxy-network:
    external: true
