services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:${VERSION}
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
      - UMASK=0022
    volumes:
      - ${PATH1}:/config
    restart: unless-stopped
    networks:
      - proxy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.prowlarr.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.prowlarr.entrypoints=websecure
      - traefik.http.routers.prowlarr.tls.certresolver=myresolver
      - traefik.http.services.prowlarr.loadbalancer.server.port=9696
networks:
  proxy-network:
    external: true
