services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:${VERSION}
    container_name: audiobookshelf
    environment:
      - TZ=Europe/Budapest
    volumes:
      - ${AUDIOBOOKSPATH}:/audiobooks
      - ${PODCASTSPATH}:/podcasts
      - ${CONFIGPATH}:/config
      - ${METADATAPATH}:/metadata
    restart: unless-stopped
    networks:
      - proxy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.audiobookshelf.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.audiobookshelf.entrypoints=websecure
      - traefik.http.routers.audiobookshelf.middlewares=crowdsec@docker
      - traefik.http.services.audiobookshelf.loadbalancer.server.port=80
networks:
  proxy-network:
    external: true
