services:
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:${VERSION}
    restart: unless-stopped
    volumes:
      - ${PATH1}:/var/run/docker.sock # Optional, only if you want docker integration
      - ${PATH2}:/appdata
    environment:
      - SECRET_ENCRYPTION_KEY=${KEY}
    networks:
      - proxy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.homarr.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.homarr.entrypoints=websecure
      - traefik.http.routers.homarr.tls.certresolver=myresolver
      - traefik.http.services.homarr.loadbalancer.server.port=7575
networks:
  proxy-network:
    external: true
